language: generic

env:
  - DOCKER_REPO=pfav/minipaint

services:
  - docker

before_install:
  - docker build -t $(echo $DOCKER_REPO) .

deploy:
  provider: script
  script: bash docker_push $(echo $DOCKER_REPO) latest
  on:
    branch: master
